# Generated by Django 4.2.2 on 2023-07-31 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_url', models.URLField()),
                ('video_name', models.CharField(blank=True, max_length=255, null=True)),
                ('time_downloaded', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
